name: Security Checks

on:
    push:
      branches:
        - staging
        - master
        - security-check
    schedule:
        - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  dast:
    name: DAST with OWASP ZAP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://staging.cromatic.bio'