name: Sentry

on:
  push:
    branches:
      - staging
      - master

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

jobs:
  upload-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: 💡 Install dependencies
        run: yarn --frozen-lockfile
      - name: 👷 Build
        run: yarn build
      - name: 💉 Inject debug ids
        run: sentry-cli sourcemaps inject --org cromatic --project octavian ./dist
      - name: 🆙 Upload source maps
        run: |
          if [ ${{ github.ref }} == "refs/heads/master" ]; then
            yarn sentry-cli sourcemaps upload --release production --org cromatic --project octavian ./dist
          elif [ ${{ github.ref }} == "refs/heads/staging" ]; then
            yarn sentry-cli sourcemaps upload --release staging --org cromatic --project octavian ./dist
          else
            yarn sentry-cli sourcemaps upload --release development --org cromatic --project octavian ./dist
          fi

  release-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Sentry production release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: getsentry/action-release@v1
        with:
          environment: production
      - name: Create Sentry staging release
        if: ${{ github.ref == 'refs/heads/staging' }}
        uses: getsentry/action-release@v1
        with:
          environment: staging
