name: Upload Sentry Source Maps

on:
  push:
    branches:
      - staging
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Set ENV based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "Setting ENV to production for master branch"
            echo "NODE_ENV=production" >> $GITHUB_ENV
          elif [ ${{ github.ref }} == "refs/heads/staging" ]; then
            echo "Setting ENV to for staging branch"
            echo "NODE_ENV=staging" >> $GITHUB_ENV
          else
            echo "Setting ENV to for default case"
            echo "NODE_ENV=development" >> $GITHUB_ENV
          fi
    - name: 💡 Install dependencies
      run: yarn --frozen-lockfile
    - name: 👷 Build
      run: yarn build
    - name: 🤖 Upload Source Maps
      run: yarn sentry:sourcemaps
